---
- hosts: localhost
  tasks:
  - include_vars:
      file: /home/ec2-user/cart1008/ansible/myvars.yaml
  - name: Create a AWS Keypair
    ec2_key:
      region: "{{ awsregion }}"
      name: my_keypair
      key_material: "{{ lookup('file', '/home/ec2-user/.ssh/id_rsa.pub') }}"
  - name: Create a Security group for EC2
    ec2_group:
      name: websg
      description: web server security Group
      vpc_id: "{{ vpcid }}"
      region: "{{ awsregion }}"
      rules:
        - proto: tcp
          from_port: 8080
          to_port: 8080
          cidr_ip: 0.0.0.0/0
        - proto: tcp
          from_port: 22
          to_port: 22
          cidr_ip: 0.0.0.0/0
  - ec2_instance:
      name: "webserver"
      region: "{{ awsregion }}"
      key_name: my_keypair
      vpc_subnet_id: subnet-0d280928a391d7730
      instance_type: t2.micro
      security_group: websg
      network:
        assign_public_ip: true
      image_id: ami-02354e95b39ca8dec
      tags:
        Name: webserver